#!/bin/sh

set -e

EXIT=0
check_installed(){
    if ! command -v "$1" >/dev/null 2>&1;then
        echo "$2" not installed && EXIT=1
    fi
}
check_installed "webpageshot" "webpageshot"
check_installed "webpagedump" "webpagedump"
check_installed "convert" "imagemagic"
[ "$EXIT" = 1 ] && exit 1

[ -d images.bkp ] && rm -r images.bkp
[ -d bad-imaged ] && rm -r bad-images
cp -r images images.bkp

echo "Fetching.."
./scripts/genimages
echo "Cropping.."
./scripts/cropimages
echo "Filtering.."
./scripts/filterimages
echo "Generating readme.."
./scripts/genreadme > README.md

./scripts/stagechanged
