#!/bin/sh

set -e

mkdir -p bad-images
for image in images/*; do
    DOMINANT_COLOR="$(convert "$image" -scale 50x50! -depth 8 +dither -colors 8 -format "%c" histogram:info: |\
        sed -n 's/^[ ]*\(.*\):.*[#]\([0-9a-fA-F]*\) .*$/\1,#\2/p' | sort -r -n -k 1 -t "," | head -n1)"

    if echo "$DOMINANT_COLOR" | grep -q '#F5F5F5';then
        echo "Filterd $image" && mv "$image" "bad-images/$(basename "$image")"
    fi
done
