#!/bin/sh

set -e

echo "# Programmingfonts Screenshots"
echo "\nI got tired of waiting for the fonts to load.\n\n"
echo "## Dependencies\n\n"
echo "- [webpageshot](https://github.com/meain/webpageshot)\n"
echo "- [webpagedump](https://github.com/meain/webpagedump)\n"
echo "- [imagemagic](https://www.imagemagick.org/)\n"
echo "\n## Images"
for image in images/*; do
    BN="$(basename "$image" | cut -d'.' -f1)"
    LINK="[$BN](https://app.programmingfonts.org/#$BN)"
    echo "\n\n### $LINK\n\n![$image](https://github.com/meain/programmingfonts-screenshots/raw/master/$image)"
done
